# Generated by Django 5.0.6 on 2024-05-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='numOfViews',
            new_name='viewCount',
        ),
    ]
