# Generated by Django 5.0.6 on 2024-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/default.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
