# Generated by Django 5.0.6 on 2024-06-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('repetitions',)},
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
