# Generated by Django 5.0.6 on 2024-06-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_tags_options_post_tags_tags_repetitions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='repetitions',
        ),
    ]
